---
# file: site.yml
- include: dataservers.yml
- include: appservers.yml
- include: webservers.yml
#- include: appservers-analytics.yml
#- include: appservers-monitoring.yml
- include: appservers-services.yml
