---
- name: Install OS Libraries
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - libXrender
   - libSM
   - libICE
   - libXext
   - fontconfig
   - cups-libs

- name: Create alfresco group
  group: name={{ alfresco_group }} state=present

- name: Create alfresco user
  user: name={{ alfresco_user }} home={{ alfresco_user_home }} uid={{ alfresco_uid }} shell=/bin/sh group={{ alfresco_group }} state=present

#- name: Download alfresco enterprise
#  file: ls /tmp/alfresco-enterprise-5.0-installer-linux-x64.bin state=present 
#  shell: 'wget  "https://process.alfresco.com/r/amazon/edl/?p=5.0/{{ alfresco_version }}-build-{{ alfresco_build }}&f=alfresco-enterprise-5.0-installer-linux-x64.bin" -O /tmp/alfresco-enterprise-5.0-installer-linux-x64.bin creates=/tmp/alfresco-enterprise-5.0-installer-linux-x64.bin'
#  register: alfresco_downloaded

- name: Create alfresco top level directory
  file: path={{ alfresco_home }} state=directory owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755

- name: Install alfresco unattended
#  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: '/tmp/alfresco-enterprise-5.0-installer-linux-x64.bin --prefix {{ alfresco_home }} --unattendedmodeui none --mode unattended --debuglevel 0 --enable-components libreofficecomponent,alfrescosolr4 --disable-components postgres,alfrescogoogledocs --jdbc_url "jdbc:mysql://10.128.108.18:3306/dbname?useUnicode=yes&amp;characterEncoding=UTF-8" --jdbc_driver org.gjt.mm.mysql.Driver --jdbc_database {{alfresco_db_name}} --jdbc_username {{alfresco_db_user}} --jdbc_password {{alfresco_db_password}} --alfresco_ftp_port 2121 --alfresco_admin_password admin --tomcat_server_directory {{alfresco_home}}/tomcat --tomcat_server_domain 127.0.01 --tomcat_server_port 8080 --tomcat_server_shutdown_port 8005 --tomcat_server_ssl_port 8443 --tomcat_server_ajp_port 8009 --alfresco_ftp_port 21 --alfresco_rmi_port 50500 --baseunixservice_install_as_service 1 --baseunixservice_script_name alfresco --libreoffice_port 8100 --alfrescocustomstack_services_startup demand' 
  register: alfresco_installed
#  when: alfresco_downloaded|changed


- name: Download mysql java-connector
  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: 'wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
      -O /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz creates=/tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz'
  register: mysqlconnector_downloaded

- name: Extract mysql-java-connector
  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: 'tar xzf /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz -C /tmp'
  when: mysqlconnector_downloaded|changed

- name: Install mysql-java-connector
  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: 'mv /tmp/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar /opt/alfresco/tomcat/lib/ && chown alfresco:alfresco /opt/alfresco/tomcat/lib/mysql-connector-java-5.1.31-bin.jar' 
  when: mysqlconnector_downloaded|changed

- name: Cleanup mysql-java-connector
  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: 'rm -rf /tmp/mysql-connector-java-{{ mysql_connector_version }}'

- name: Start alfresco server
  sudo: yes
  sudo_user: '{{ alfresco_user }}'
  shell: 'sudo {{ alfresco_home }}/alfresco.sh start' 
  when: alfresco_installed|changed

#- name: Cleanup alfresco unzipped
#  shell: 'rm -rf /tmp/alfresco-enterprise-5.0-installer-linux-x64.bin' 
