---
- name: Install OS Libraries
  sudo: True
  yum: name={{ item }} state=present
  with_items:
   - libXrender
   - libSM
   - libICE
   - libXext
   - fontconfig
   - cups-libs

- name: Download alfresco enterprise
  shell: 'wget https://process.alfresco.com/r/amazon/edl/?p=5.0/{{ alfresco_version }}-build-{{ alfresco_build }}&f=alfresco-enterprise-{{ alfresco_version }}-installer-linux-x64.bin -O /tmp/alfresco-enterprise-{{ alfresco_version }}-installer-linux-x64.bin creates=/tmp/alfresco-enterprise-{{ alfresco_version }}-installer-linux-64.bin'
  register: alfresco_downloaded

- name: Install alfresco licenses, licenses and readme
  shell: cp -rf /tmp/alfresco/bin /tmp/alfresco/licenses /tmp/alfresco/README.txt {{ alfresco_user_home }}/
  when: alfresco_extracted|changed

- name: Install alfresco unattended
  shell: 'sudo ./alfresco-enterprise-4.2.0.3-installer-linux-x64.bin --prefix {{ alfresco_user_home }} \
 
--unattendedmodeui none --mode unattended --debuglevel 0 \
 
--enable-components javaalfresco,alfrescosharepoint,alfrescogoogledocs,libreofficecomponent \
--disable-components postgres \
--jdbc_url "jdbc:mysql://10.128.108.18:3306/dbname?useUnicode=yes&characterEncoding=UTF-8" \
--jdbc_driver org.gjt.mm.mysql.Driver --jdbc_database dbname --jdbc_username dbuser \
--jdbc_password dbpassword --alfresco_ftp_port 2121 \
--alfresco_admin_password alfrescoadminpassword --baseunixservice_install_as_service 0 \
--alfrescocustomstack_services_startup demand'
  when: alfresco_extracted|changed

- name: Cleanup alfresco unzipped
  file: path=/tmp/alfresco state=absent
  when: alfresco_extracted|changed

- name: Download mysql java-connector
  shell: 'wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
      -O /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz creates=/tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz'
  register: mysqlconnector_downloaded

- name: Extract mysql-java-connector
  shell: 'tar xzf /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz -C /tmp'
  when: mysqlconnector_downloaded|changed

- name: Install mysql-java-connector
  shell: 'mv /tmp/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar /opt/alfresco/tomcat/lib/ && chown alfresco:alfresco /opt/alfresco/tomcat/lib/mysql-connector-java-5.1.31-bin.jar'
  when: mysqlconnector_downloaded|changed

- name: Cleanup mysql-java-connector
  shell: 'rm -rf /tmp/mysql-connector-java-{{ mysql_connector_version }}'

- name: Install alfresco init script
  template: src=alfresco dest=/etc/init.d/alfresco owner=root group=root mode=0755
  when: alfresco_extracted|changed

- name: Install alfresco global configuration
  template: src=alfresco-global.properties dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco-global.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed

- name: Install alfresco logging configuration
  template: src=custom-log4j.properties dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco/extension/custom-log4j.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed

- name: Set alfresco file owner
  shell: chown -R {{ alfresco_user }}:{{ alfresco_group }} {{ alfresco_user_home }} && chown -R {{ alfresco_user }}:{{ alfresco_group }} /opt/apache-tomcat-{{ tomcat_version }}
  when: alfresco_extracted|changed

- name: Start alfresco server
  service: name=alfresco state=started
  when: alfresco_extracted|changed

- name: Wait for alfresco war deploy
  wait_for: path=/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/web.xml
  when: alfresco_extracted|changed

- name: Relax security constraint for solr http comunication
  copy: src=web.xml dest={{ alfresco_user_home }}/tomcat/webapps/alfresco/WEB-INF/web.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed

- name: Restart alfresco server
  service: name=alfresco state=restarted
  when: alfresco_extracted|changed 
